import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import ContactBookLayout from "../components/ContactBookLayout";
import BookPage from "../components/BookPage";
import Loader from "../components/Loader";
import { createContact, getContact, updateContact } from "../services/contacts";
import { getGroups } from "../services/groups";

const blank = { name: "", phone: "", email: "", address: "", category: "", notes: "", group: "" };
export default function ContactForm({ editing = false }) {
  const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(blank); const [groups, setGroups] = useState([]); const [loading, setLoading] = useState(editing); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getGroups(), editing ? getContact(id) : Promise.resolve({ data: { data: blank } })]).then(([groupsResponse, contactResponse]) => { setGroups(groupsResponse.data.data); const contact = contactResponse.data.data; setForm({ name: contact.name || "", phone: contact.phone || "", email: contact.email || "", address: contact.address || "", category: contact.category || "", notes: contact.notes || "", group: contact.group?._id || "", photo: contact.photo || "" }); }).catch(() => setError("Unable to load this notebook page.")).finally(() => setLoading(false)); }, [editing, id]);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const choosePhoto = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return setError("Please choose an image file."); if (file.size > 3 * 1024 * 1024) return setError("Choose an image smaller than 3 MB."); const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const canvas = document.createElement("canvas"); const scale = Math.min(1, 600 / Math.max(image.width, image.height)); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale); canvas.getContext("2d").drawImage(image, 0, 0, canvas.width, canvas.height); setForm((current) => ({ ...current, photo: canvas.toDataURL("image/jpeg", .82) })); }; image.src = reader.result; }; reader.readAsDataURL(file); };
  const submit = async (event) => { event.preventDefault(); setError(""); if (!form.name.trim() || !form.phone.trim()) return setError("Name and phone are required."); setSaving(true); try { const response = editing ? await updateContact(id, form) : await createContact(form); navigate(`/contacts/${response.data.data._id}`); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to save contact."); } finally { setSaving(false); } };
  if (loading) return <ContactBookLayout><Loader label="Preparing a fresh page..." /></ContactBookLayout>;
  return <ContactBookLayout><BookPage className="form-page" eyebrow={editing ? "EDITING A PAGE" : "A FRESH PAGE"} title={editing ? "Edit contact" : "Add a contact"}><p className="lead-copy">Write down the details you want to remember.</p><div className="contact-form-symbols" aria-hidden="true"><span>◯</span><span>☎</span><span>✉</span><span>⌂</span></div><form className="notebook-form" onSubmit={submit}><div className="photo-picker"><div className="photo-preview">{form.photo ? <img src={form.photo} alt="Contact preview" /> : <span>+</span>}</div><div><label className="photo-button">Add person photo<input type="file" accept="image/*" onChange={choosePhoto} /></label>{form.photo && <button type="button" className="photo-remove" onClick={() => setForm({ ...form, photo: "" })}>Remove photo</button>}<small>JPG, PNG or WEBP up to 3 MB</small></div></div><div className="form-grid"><label>Full name<input name="name" value={form.name} onChange={update} placeholder="John Doe" required /></label><label>Phone<input name="phone" value={form.phone} onChange={update} placeholder="+91 98765 43210" required /></label><label>Email<input name="email" type="email" value={form.email} onChange={update} placeholder="john@example.com" /></label><label>Category<input name="category" value={form.category} onChange={update} placeholder="Family, Work..." /></label><label>Address<input name="address" value={form.address} onChange={update} placeholder="Where they live" /></label><label>Group<select name="group" value={form.group} onChange={update}><option value="">Unsorted</option>{groups.map((group) => <option key={group._id} value={group._id}>{group.name}</option>)}</select></label></div><label>Notes<textarea name="notes" value={form.notes} onChange={update} rows="5" placeholder="A little context, a birthday, a reminder..." /></label>{error && <p className="form-error">{error}</p>}<div className="form-actions"><Link className="outline-button" to={editing ? `/contacts/${id}` : "/contacts"}>Cancel</Link><button className="gold-button" disabled={saving}>{saving ? "Saving page..." : editing ? "Update contact" : "Save contact"}</button></div></form></BookPage></ContactBookLayout>;
}
