import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import Modal from "../components/Modal";
import { getContacts } from "../services/contacts";
import { createGroup, deleteGroup, getGroups, updateGroup } from "../services/groups";

export default function Groups() {
  const [groups, setGroups] = useState([]); const [counts, setCounts] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(null);
  const load = async () => { setLoading(true); setError(""); try { const [groupsResponse, contactsResponse] = await Promise.all([getGroups(), getContacts(1, 100)]); setGroups(groupsResponse.data.data); const nextCounts = {}; contactsResponse.data.data.forEach((contact) => { if (contact.group?._id) nextCounts[contact.group._id] = (nextCounts[contact.group._id] || 0) + 1; }); setCounts(nextCounts); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to load groups."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (name) => { try { if (modal.group) await updateGroup(modal.group._id, { name }); else await createGroup({ name }); setModal(null); await load(); } catch (requestError) { throw new Error(requestError.response?.data?.message || "Unable to save group."); } };
  const remove = async (group) => { if (!window.confirm(`Delete ${group.name}? Contacts in it will become unsorted.`)) return; try { await deleteGroup(group._id); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to delete group."); } };
  return <AppLayout><div className="page-heading"><div><p className="workspace-kicker">ORGANIZE</p><h2>Your groups</h2><p className="workspace-muted">Give every part of your life a useful home.</p></div><button className="primary-button" onClick={() => setModal({ group: null })}>＋ New group</button></div>{error && <div className="inline-error">{error}</div>}{loading ? <div className="state-box"><div className="spinner" />Loading groups...</div> : groups.length === 0 ? <div className="state-box"><strong>No groups yet</strong><span>Create a group to organize your contacts.</span></div> : <div className="group-grid">{groups.map((group, index) => <article className="group-card" key={group._id}><span className={`group-card-icon tone-${index % 4}`}>◌</span><div><h3>{group.name}</h3><p>{counts[group._id] || 0} contacts</p></div><div className="card-actions"><button className="text-button" onClick={() => setModal({ group })}>Edit</button><button className="text-button danger" onClick={() => remove(group)}>Delete</button></div></article>)}</div>}{modal && <GroupModal group={modal.group} onClose={() => setModal(null)} onSave={save} />}</AppLayout>;
}
function GroupModal({ group, onClose, onSave }) { const [name, setName] = useState(group?.name || ""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const submit = async (event) => { event.preventDefault(); if (!name.trim()) return setError("Group name is required."); setSaving(true); try { await onSave(name.trim()); } catch (saveError) { setError(saveError.message); } finally { setSaving(false); } }; return <Modal eyebrow={group ? "EDIT GROUP" : "NEW GROUP"} title={group ? "Rename group" : "Create a group"} onClose={onClose}><form className="modal-form" onSubmit={submit}><label className="field">Group name<input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder="Family" /></label>{error && <p className="form-error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? "Saving..." : "Save group"}</button></div></form></Modal>; }
